# Generated by Django 5.0.6 on 2025-11-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predictions/')),
                ('model_type', models.CharField(choices=[('cnn', 'CNN'), ('vgg16', 'VGG16'), ('both', 'Both')], default='vgg16', max_length=50)),
                ('predicted_class', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('prediction_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
